using UnityEngine;

namespace hairmaster.Scripts
{
    public class CharacterMovementController : MonoBehaviour
    {
        [SerializeField]
        private float speed=1;

        private float gravityModifier=-9.81f;

        //Private Data
        private CharacterInputController characterInputController;
        private Rigidbody rb;
        private Animator anim;
        private bool isRunning;
        private bool reachedGoalLine;
        private Transform endTraget;
        private Transform lookAtEndTraget;
        private bool stretchingHairPhase;
        private Vector3 revivePos;

        //Reference
        public static CharacterMovementController instance;
       
        public class RAIKLVWWAGFNRLQDDAFEVYGR
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class KQVNTALVWOBHLFECJGBUSMGOCAOWYDVKHZ
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF()
        {
            
        }
        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF GetFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(){
        var clasx = new FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF();
        return  clasx;
    }

    public string RandomStringFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU()
        {
            
        }
        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU GetIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(){
        var clasx = new IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU();
        return  clasx;
    }

    public string RandomStringIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF()
        {
            
        }
        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF GetTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(){
        var clasx = new TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF();
        return  clasx;
    }

    public string RandomStringTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF()
        {
            
        }
        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF GetEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(){
        var clasx = new EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF();
        return  clasx;
    }

    public string RandomStringEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI()
        {
            
        }
        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI GetMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(){
        var clasx = new MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI();
        return  clasx;
    }

    public string RandomStringMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf()
        {
            
        }
        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf GetSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(){
        var clasx = new SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf();
        return  clasx;
    }

    public string RandomStringSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk()
        {
            
        }
        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk GetgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(){
        var clasx = new goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk();
        return  clasx;
    }

    public string RandomStringgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EizkmfhTzQOiEEgVjEIojKPubojHDah
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EizkmfhTzQOiEEgVjEIojKPubojHDah()
        {
            
        }
        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EizkmfhTzQOiEEgVjEIojKPubojHDah GetEizkmfhTzQOiEEgVjEIojKPubojHDah(){
        var clasx = new EizkmfhTzQOiEEgVjEIojKPubojHDah();
        return  clasx;
    }

    public string RandomStringEizkmfhTzQOiEEgVjEIojKPubojHDah(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz()
        {
            
        }
        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz GetkIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(){
        var clasx = new kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz();
        return  clasx;
    }

    public string RandomStringkIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx()
        {
            
        }
        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx GetmNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(){
        var clasx = new mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx();
        return  clasx;
    }

    public string RandomStringmNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(int length)
    {
        string chars = string.Empty;
        return chars;
    }
 private void Awake()
        {
            if (!instance) instance = this;
            else if (instance != this) Destroy(this.gameObject);
            
            characterInputController = this.GetComponent<CharacterInputController>();
            CameraController.instance.setTarget(this.transform);

        }
        // Start is called before the first frame update

        public class QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw()
        {
            
        }
        public QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw GetQwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw(){
        var clasx = new QwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw();
        return  clasx;
    }

    public string RandomStringQwDRkDbmmFvYCjsTzfGNbPlHhMClNxNIizyTrziZSVMmFAomoOLmQXRALw(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf()
        {
            
        }
        public hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf GethpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf(){
        var clasx = new hpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf();
        return  clasx;
    }

    public string RandomStringhpazvxvtxoBLruTGIjzkacwVWVJOYSePaeaVxkBavRKRcRkElXqNqeZFtEcaohVf(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL()
        {
            
        }
        public TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL GetTklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL(){
        var clasx = new TklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL();
        return  clasx;
    }

    public string RandomStringTklWxZQgCvcnDgNcrFHrQaexHJGUoYjKxoeXTYANCSNUUNthNbSowlgsFnPoSwreL(int length)
    {
        string chars = string.Empty;
        return chars;
    }
        void Start()
        {
            anim = this.GetComponent<Animator>();
            rb = this.GetComponent<Rigidbody>();
            startPlay();
        }

        // Update is called once per frame
        void Update()
        {
            if(canPlay())
                move();
        }
        private void move()
        {
            if (!reachedGoalLine && isRunning)
            {
                Vector3 newPos = this.rb.position + characterInputController.getNewPos();
                this.rb.MovePosition(Vector3.MoveTowards(this.rb.position, Vector3.Slerp(this.rb.position, newPos, .7f), 8f));
            }else if (reachedGoalLine)
            {
                Vector3 directionToEndTraget = endTraget.position - this.transform.position;
                directionToEndTraget *= Time.deltaTime * 2f;
                this.transform.position += directionToEndTraget;
                float distanceToEnd = Vector3.Distance(this.transform.position, endTraget.position);
                if (distanceToEnd < 1f &&  !stretchingHairPhase)
                {
                    stretchingHairPhase = true;
                    anim.SetBool("Run",false);
                    //anim.SetTrigger("Dance0");
                    anim.SetTrigger("Laying");
                    anim.SetTrigger("Dance0");
                    this.rb.isKinematic = true;
                    this.transform.GetComponentInChildren<HairController>().resetHair();
                    this.transform.localEulerAngles = new Vector3(0, 180, 0);
                    Invoke("stretchHair", 3f);
                    // transform.localRotation = Quaternion.Lerp(this.transform.rotation, lookAtEndTraget.rotation, 1);
                }
                this.rb.velocity = Vector3.zero;

            }

        }class Book
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            public Book(string title, string publisher, string? isbn)
                => (Title, Publisher, Isbn) = (title, publisher, isbn);

            public Book(string title, string publisher)
                : this(title, publisher, null) { }

           
        public class HBAXPTUXIQMQBAVHXWEWTGMDYLBLQRPVHP
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}
 public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Bookxhuwxccw
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Bookxchuwa
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Bookxchcuwaxhua
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Bookxchcuwaxhuachx
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class HCWIoajciw
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class PowscqCHUW
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class HCWIoajciwCHOAW
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class HCWIoajciwCHOAWowis
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Owicuaow
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class OwicuaowScuwa
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class IWUCOASWkdkow
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class UCIQOAXS
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class UCIQOAXSCJIWhcuiw
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class UCIQOAXSCJIWhcuiwxhiaiw
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class MCOwjiaxXjoar
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class MCOwjiaxXjoarAIXA
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class MCOwjiaxXjoarAIXACHUW
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class MCOwjiaxXjoarAIXAOCiwa
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
    
        class KCOZLKSOwa
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        class Bookxchcuwa
        {
            public string Title { get; }
            public string Publisher { get; }
            public string? Isbn { get; }
            

            public void Deconstruct(out string title, out string publisher, out string? isbn)
                => (title, publisher, isbn) = (Title, Publisher, Isbn);

            public override string ToString() => Title;
        }
        void FixedUpdate()
        {
            if (isRunning && canPlay()&& !reachedGoalLine)
                rb.velocity = (Vector3.forward * speed
#if UNITY_EDITOR
            *3
#endif
                               
                               + Vector3.up * gravityModifier);
            else
            {
                rb.velocity = Vector3.zero;

            }

        }
        private void startPlay()
        {
            //anim.SetBool("Run", true);
        }
        public void updateMovementState(bool currentState)
        {
            isRunning = currentState;
            if (isRunning)//Enable Run Animation
                anim.SetBool("Run", true);
            else //Disable Running Animation
                anim.SetBool("Run", false);
        }
        private void OnTriggerEnter(Collider other)
        {
            if (other.gameObject.CompareTag("Finish"))
            {
                this.rb.velocity = Vector3.zero;
                HairController.instance.resetHair();
                endTraget = other.GetComponent<FinishController>().getFinishTarget();
                lookAtEndTraget= other.GetComponent<FinishController>().getFinishLookAtTarget();
                characterInputController.enabled = false;
                reachedGoalLine = true;
            }
            if (other.gameObject.CompareTag("Fail"))
            {
                if (other.transform.childCount > 0)
                    revivePos = other.transform.GetChild(0).position;
                else
                    revivePos = PlayerPointController.instance.getPos();
                GameManager.instance.endPlay();
                UiManager.instance.playerLoose();
                anim.SetTrigger("Fail");

            }
        }
        private bool canPlay()
        {
            return GameManager.instance.currentGameState == GameManager.GameState.play;
        }
        private void stretchHair()
        {
            HairController.instance.stretchHair();
        }
        public void revive()
        {

            this.transform.position = revivePos;
            anim.SetBool("idle",true);
            GameManager.instance.startPlay();

        }

    }
}
