using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace CubeSurfing.scripts{
public class GameManager : MonoBehaviour
{
    public GameObject idlePanel;
    public GameObject loosePanel;
    public GameObject winPanel;
    public static GameManager Instance;
    public GameObject scorepopup;
    public Text sceneIndex;
    public GameObject ingame;
    public GameObject shopMessage;
    public Text scoreText;
    public GameObject nextButton;
    public Text globalScore ;
     public Text finishScoreHolder ;

    
     
 
        public class GGXNCXSSRDUVTGOTSFKB
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class IBGWIUDXRSUSNQLZOXS
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class WKKMSFHNJGCWBPGKXYGLEVOCETTNN
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class FDONFHMIEIKAWPYHUVITPUEOWGMZYSK
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class PBYQGUUEMIWXGRRJKXEBEXQSDCCGFB
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class YAUJCUMUNNMLHTDXOAKDJIWNIJE
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}
   private int currentScore;
    [Header("Game End")]
    [SerializeField] CoinManger coinM;
    [SerializeField] Transform coinT;
    [SerializeField] Text collectedCoin;      
    int oldScore;
    // Start is called before the first frame update
    void Start()
    {
      
        if (Instance == null)
        {
            Instance = this;
        }
        else
        {
            if (Instance != this)
                Destroy(this);
        }
       //GoogleAdMobController.instance.RequestAndLoadInterstitialAd();
          //Advertisements.Instance.Initialize(); 
          
          
          
          
       ingame.SetActive(false);
        int i = PlayerPrefs.GetInt("current_level");
        if(SceneManager.GetActiveScene().buildIndex!=i){
           // SceneManager.LoadScene(i);
        }
          setLevel();
           oldScore=PlayerPrefs.GetInt("current_score");
           globalScore.text=oldScore.ToString();
           scoreText.text="0";
          
      //  loadscene();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
   
        public class CFKACJBOGNFLROBUSRMI
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class QSAZHIUWUPLGILKBSTHDHBAO
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class HBAXPTUXIQMQBAVHXWEWTGMDYLBLQRPVHP
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}
 public void gameStart()
    {
        if (!GameItemManager.Instance.IsEnoughCoin())
        {
            return;
        }
          ingame.SetActive(true);
        CharactereController.state = CharactereController.gameState.playing;
        idlePanel.SetActive(false);
        //tapToPlaySound.Play();
    }
    public void gameloose()
    {
       //  GoogleAdMobController.instance.RequestAndLoadInterstitialAd();
         //looseSound.Play(); 
         ingame.SetActive(false);
         Invoke("activateLossePanel",.2f);
        //GameItemManager.Instance.UseCoin(1);
        
    }
    public class Gẵccawsw
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public class ỌIuvklaw
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public class KLJhamwnx
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public class LKjaiowklx
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public class KLjaoiwx
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public void gameWin()
    {
        
      
       ingame.SetActive(false);
       finishScoreHolder.text="0";
       collectedCoin.text=currentScore.ToString();
       oldScore+=currentScore;
        PlayerPrefs.SetInt("current_score",oldScore);
        winPanel.SetActive(true);
        // winSound.Play();
        Invoke("activateNext",2f);
    }
    public void doubleMoney(){
        //Advertisements.Instance.ShowRewardedVideo(CompleteMethod);
    }
   
        public class HMDHOJYYZAOYXRVUYNMPRWAKKN
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class OOERZVLWYGZMNZJZOOBPALZGUQGHBPBAA
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF()
        {
            
        }
        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF GetFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(){
        var clasx = new FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF();
        return  clasx;
    }

    public string RandomStringFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU()
        {
            
        }
        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU GetIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(){
        var clasx = new IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU();
        return  clasx;
    }

    public string RandomStringIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF()
        {
            
        }
        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF GetTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(){
        var clasx = new TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF();
        return  clasx;
    }

    public string RandomStringTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF()
        {
            
        }
        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF GetEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(){
        var clasx = new EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF();
        return  clasx;
    }

    public string RandomStringEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI()
        {
            
        }
        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI GetMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(){
        var clasx = new MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI();
        return  clasx;
    }

    public string RandomStringMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf()
        {
            
        }
        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf GetSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(){
        var clasx = new SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf();
        return  clasx;
    }

    public string RandomStringSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk()
        {
            
        }
        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk GetgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(){
        var clasx = new goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk();
        return  clasx;
    }

    public string RandomStringgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EizkmfhTzQOiEEgVjEIojKPubojHDah
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EizkmfhTzQOiEEgVjEIojKPubojHDah()
        {
            
        }
        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EizkmfhTzQOiEEgVjEIojKPubojHDah GetEizkmfhTzQOiEEgVjEIojKPubojHDah(){
        var clasx = new EizkmfhTzQOiEEgVjEIojKPubojHDah();
        return  clasx;
    }

    public string RandomStringEizkmfhTzQOiEEgVjEIojKPubojHDah(int length)
    {
        string chars = string.Empty;
        return chars;
    }
 private void CompleteMethod(bool completed, string advertiser)
    {
      Debug.Log("Closed rewarded from: "+advertiser+" -> Completed " + completed);
    if(completed == true)
    {
        oldScore*=2;
        PlayerPrefs.SetInt("current_score",oldScore);
        next01();
    }
     else
    {
       //no reward
    }
    }
    private void activateNext(){
        winCoinAnimate();
        animateScore();
        nextButton.SetActive(true);
    }
    public void next01(){
    	//buttonSound.Play();
    	 loadscene();
    }
    public void next()
    {
       // addLevel();
    	//buttonSound.Play();
    	//Advertisements.Instance.ShowInterstitial();
        
        
        
        
        loadscene();
    }
    public void retry()
    {
        loadscene();

    }
    public void addScore(Vector3 position)
    {
        Instantiate(scorepopup, Camera.main.WorldToScreenPoint(position), Quaternion.identity,this.transform);
    }
    public void addLevel()
    {
        int i = PlayerPrefs.GetInt("current_level",0);
        i++; 
        PlayerPrefs.SetInt("current_level", i);
    }public class Llcaowksx
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public class Acwvsddeqw
    {
        public int A;
        public int B;
        public string C;
        public bool X;
        private double D;
        private float E;

        public void ALKJXCL()
        {
      
        }
    }
    public void loadscene()
    {
        GameItemManager.Instance.ReloadLevel();
    }
    class Book
    {
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }
        public Book(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public Book(string title, string publisher)
            : this(title, publisher, null) { }

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }
    private void setLevel(){
         int i = PlayerPrefs.GetInt("current_level");
          sceneIndex.text = "Level : " + i;
    }
    private void activateLossePanel(){
           //  loosePanel.SetActive(true);
             loadscene();
    }
    public void goShopping(){
      

    }
    private void hideMessage(){
         shopMessage.SetActive(false);

    }
    public void increementMoney(){
        currentScore+=5;
        scoreText.text=currentScore.ToString();

    }
    private void winCoinAnimate(){
      
        
       
        
    }

    private void animateScore(){
       
        for(int i=0;i<currentScore+1;i++){
           finishScoreHolder.text=i.ToString();
         
        }
       
    }
   

}

}
