using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Controll : MonoBehaviour
{
    public GameObject breakWay;
    public GameObject gaz;
    public GameObject hitEffect;
    public float speed;
 
        public class NCEENQXLWWQ
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class EVHVBRXSWIHU
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class AXXXSPYSVCLKVHDRKGDINHQXFAVYHYVBTD
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class CLCFZKQVZIAZBPCEZVDXCQHMXJKSH
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class RSCTHGDSCSIRXELEKJUZLXXCZIGXMVK
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class GGXNCXSSRDUVTGOTSFKB
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class GZAPJFOIIPUNIYPQVVT
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class WKKMSFHNJGCWBPGKXYGLEVOCETTNN
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class FDONFHMIEIKAWPYHUVITPUEOWGMZYSK
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class PBYQGUUEMIWXGRRJKXEBEXQSDCCGFB
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class DCFVTNKLQHGTAYDPDMPVHB
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class YAUJCUMUNNMLHTDXOAKDJIWNIJE
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}
   private float imp;

    public class ProductItem
    {
        public string id;
        public Sprite icon;
        public string price;
        public string title;

        public void Acoakwos()
        {
            id = price + title;
        }
    }
    public class Akjhcuiaw
    {
        public string id;
        public Sprite icon;
        public string price;
        public string title;

        public void Acoakwos()
        {
            id = price + title;
        }
    }
    public class Acawasczx
    {
        public string id;
        public Sprite icon;
        public string price;
        public string title;

        public void Acoakwos()
        {
            id = price + title;
        }
    }
    public class Awcbhse
    {
        public string id;
        public Sprite icon;
        public string price;
        public string title;

        public void Acoakwos()
        {
            id = price + title;
        }
    }
    private bool carCrash;

    private int crossed;
    
    private GameObject t_cross;
    private GameObject t_cross2;
    // Start is called before the first frame update
    void Start()
    {
        imp = 0.5f;

        t_cross = GameObject.Find("t_cross");
        t_cross2 = GameObject.Find("t_cross2");
        
        var cr = Instantiate(GameObject.Find("_SkinsCar").GetComponent<skinsCar>().carSkin[PlayerPrefs.GetInt("skin")],
            transform.position, transform.rotation);
        
        cr.transform.localEulerAngles = new Vector3(0,180,0);
        cr.transform.parent = transform;
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        transform.Translate(Vector3.forward * Time.fixedDeltaTime * speed * imp);

        if (carCrash == false)
        {
            if (Input.GetMouseButton(0))
            {
                imp += Time.deltaTime * 3;
                if (Input.GetMouseButtonDown(0))
                {
                    Instantiate(gaz, transform.position, gaz.transform.rotation);
                    
                    GameObject.Find("Gas").GetComponent<AudioSource>().Play();
                }
            }
            else
            {
                if (Input.GetMouseButtonUp(0) && imp > 1f)
                {
                    var bw = Instantiate(breakWay, transform.position, gaz.transform.rotation);
                    bw.transform.parent = transform;
                }

                imp -= Time.deltaTime * 3;
            }

            if (imp > 1.2) imp = 1.2f;
            if (imp < 0.4f)
            {
                imp = 0.4f;
            }
        }
        else
        {
            speed *= 0.97f;
        }
    }
    
    void OnCollisionEnter(Collision collision)
    {
        if (carCrash == false)
        {
            collision.gameObject.GetComponent<OnCar>().carCrash = true;
            carCrash = true;

            Instantiate(hitEffect, transform.position + new Vector3(0, 5, 0), hitEffect.transform.rotation);

            GameObject.Find("endLevel").GetComponent<endLevel>().levelEnded = true;

            if (PlayerPrefs.GetInt("score") < crossed)
            {
                PlayerPrefs.SetInt("score", crossed);
            }

        }
        GameObject.Find("Crash").GetComponent<AudioSource>().Play();
    }
    
   
        public class HMDHOJYYZAOYXRVUYNMPRWAKKN
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class BHBLFRLHWKRLKHKDMFRXSOUBICQRQ
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class KQVNTALVWOBHLFECJGBUSMGOCAOWYDVKHZ
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class GVLUDIOLNJCZFLIWMJILAMHNLHTJO
			{
				private int buaquadi;
				private string chusx;
				public float gmac;
				private double mciajx;

				public int getX()
				{
					return buaquadi;
				}
			}

        public class FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF()
        {
            
        }
        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF GetFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(){
        var clasx = new FJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF();
        return  clasx;
    }

    public string RandomStringFJALHUJOTCWIEXZBEHRMWAAHKYGHIHPWBMHPYVJASMYXFWTDPF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU()
        {
            
        }
        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU GetIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(){
        var clasx = new IZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU();
        return  clasx;
    }

    public string RandomStringIZPTVTGADKGSHWZZPVLPISYSDPAOMHXSU(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF()
        {
            
        }
        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF GetTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(){
        var clasx = new TUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF();
        return  clasx;
    }

    public string RandomStringTUMBJEXVQHUMKDSNDOYIBALHOXYNJGLGOHXCEF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF()
        {
            
        }
        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF GetEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(){
        var clasx = new EAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF();
        return  clasx;
    }

    public string RandomStringEAMKDDLTRWLBRQYOQYFCONEXBNSIXTEZUQEWBPNTSTFNDF(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI()
        {
            
        }
        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI GetMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(){
        var clasx = new MSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI();
        return  clasx;
    }

    public string RandomStringMSUEWCKMYABAAWEUZNKGLZUJIXVTGHEEHELKLSVJABI(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf()
        {
            
        }
        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf GetSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(){
        var clasx = new SiVJUgxMSTCpzCNpQgyFpfFEMqnpbf();
        return  clasx;
    }

    public string RandomStringSiVJUgxMSTCpzCNpQgyFpfFEMqnpbf(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk()
        {
            
        }
        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk GetgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(){
        var clasx = new goMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk();
        return  clasx;
    }

    public string RandomStringgoMknmXoAIzAQGOuDcPxZNNBcCaJKxOtAxnssNOpdhPBNmUxdk(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class EizkmfhTzQOiEEgVjEIojKPubojHDah
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public EizkmfhTzQOiEEgVjEIojKPubojHDah()
        {
            
        }
        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public EizkmfhTzQOiEEgVjEIojKPubojHDah(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public EizkmfhTzQOiEEgVjEIojKPubojHDah GetEizkmfhTzQOiEEgVjEIojKPubojHDah(){
        var clasx = new EizkmfhTzQOiEEgVjEIojKPubojHDah();
        return  clasx;
    }

    public string RandomStringEizkmfhTzQOiEEgVjEIojKPubojHDah(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz()
        {
            
        }
        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz GetkIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(){
        var clasx = new kIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz();
        return  clasx;
    }

    public string RandomStringkIrdOrlSsaysGOwPQHAVCfergYclkCzzxITCRbGpdILXjwYrLIGecczFezwqPz(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx()
        {
            
        }
        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx GetmNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(){
        var clasx = new mNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx();
        return  clasx;
    }

    public string RandomStringmNKeffDtMYkYrNoeVgmDtJPruuIFUvrhcOalxHEvymSyQPxAwObDJtEcx(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ()
        {
            
        }
        public AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ GetAEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ(){
        var clasx = new AEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ();
        return  clasx;
    }

    public string RandomStringAEKginenRrdSuSaeVkIDzByTadxHjmyrZeCegDjsSCfRSEAIOFZtLcnzGrFEpXEfsmtQ(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR()
        {
            
        }
        public GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR GetGrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR(){
        var clasx = new GrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR();
        return  clasx;
    }

    public string RandomStringGrfgODsngghwjucemzzSKCJyBrGNfOnkZCaIARtqibndSdbyR(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa()
        {
            
        }
        public MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa GetMQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa(){
        var clasx = new MQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa();
        return  clasx;
    }

    public string RandomStringMQRMYEIyAiZMVuBUJoYCqFdNCmjcgQtaa(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class IKPoLnSWflsxFxHlFBIxQndzcKdeNz
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public IKPoLnSWflsxFxHlFBIxQndzcKdeNz()
        {
            
        }
        public IKPoLnSWflsxFxHlFBIxQndzcKdeNz(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public IKPoLnSWflsxFxHlFBIxQndzcKdeNz(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public IKPoLnSWflsxFxHlFBIxQndzcKdeNz GetIKPoLnSWflsxFxHlFBIxQndzcKdeNz(){
        var clasx = new IKPoLnSWflsxFxHlFBIxQndzcKdeNz();
        return  clasx;
    }

    public string RandomStringIKPoLnSWflsxFxHlFBIxQndzcKdeNz(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD()
        {
            
        }
        public QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD GetQDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD(){
        var clasx = new QDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD();
        return  clasx;
    }

    public string RandomStringQDIWKnQsQBmwXrsNjrOfUAIefZfjrzsnkTsWNZMeqZoCkOpcRfPPKD(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ()
        {
            
        }
        public lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ GetlyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ(){
        var clasx = new lyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ();
        return  clasx;
    }

    public string RandomStringlyauStJHkJfhjPTPJvQWujGLtcQSBnCKsLYOVenzBVNJsusLVxwLmJ(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV()
        {
            
        }
        public yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV GetyTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV(){
        var clasx = new yTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV();
        return  clasx;
    }

    public string RandomStringyTozfVrsHGzmEBuzbJmMQUfeoNvBKNMcnTAtFOVZiFV(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww()
        {
            
        }
        public dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww GetdhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww(){
        var clasx = new dhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww();
        return  clasx;
    }

    public string RandomStringdhzNwJPkcypaUdvLFSXwDPjQxptWbqTGVYhaNPDQnAzJuWOHvnCUxlHNyjPHPsJlfjEww(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja()
        {
            
        }
        public uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja GetuhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja(){
        var clasx = new uhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja();
        return  clasx;
    }

    public string RandomStringuhMwNYWsgnyRpvsquWrLURYalzGJpzUlbyxja(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo()
        {
            
        }
        public HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo GetHFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo(){
        var clasx = new HFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo();
        return  clasx;
    }

    public string RandomStringHFOUVSXVoBSvjbYEtHLhUjQfmQOFYZghNcIUqtwsCySmZFusKo(int length)
    {
        string chars = string.Empty;
        return chars;
    }

        public class mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu
    {
        private int buaquadi;
        private string chusx;
        public float gmac;
        private double mciajx;

        public int getX()
        {
            return buaquadi;
        }
        public string Title { get; }
        public string Publisher { get; }
        public string? Isbn { get; }

        public mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu()
        {
            
        }
        public mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu(string title, string publisher, string? isbn)
            => (Title, Publisher, Isbn) = (title, publisher, isbn);

        public mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu(string title, string publisher)
            : this(title, publisher, null) {}

        public void Deconstruct(out string title, out string publisher, out string? isbn)
            => (title, publisher, isbn) = (Title, Publisher, Isbn);

        public override string ToString() => Title;
    }

    public mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu GetmjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu(){
        var clasx = new mjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu();
        return  clasx;
    }

    public string RandomStringmjtgIJPZgiWZETlTSBpMkRqROCbIRXcMzBWGctXzvCNJMtfezfoZu(int length)
    {
        string chars = string.Empty;
        return chars;
    }
 private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.tag == "Cross" && carCrash == false)
        {
            crossed += 1;
           t_cross.GetComponent<TextMesh>().text = crossed + "";
           t_cross2.GetComponent<TextMesh>().text = crossed + "";
           t_cross.AddComponent<ScaleUpEffect>();
        }
    }
}
